name: Run Gatling Enterprise Simulation
on:
  pull_request:
    branches: [ main ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Gatling Enterprise Action
        uses: gatling/enterprise-action@v1
        with:
          api_token: ${{ secrets.GATLING_ENTERPRISE_API_TOKEN }}
          simulation_id: "FneU_Y6OMF6XoU.u-3ZWOIW75QxeG6tbhtAnd_gBBsn6djHYqJ9CKLX.YRNh_Dvk5"
